config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :articles
  post 'articles/:id/comments', to: 'comments#create', as: :comment_article
  get 'articles/comment/:id', to: 'comments#edit', as: :edit_comment_article
  patch 'articles/:id/like', to: 'articles#like', as: :like_article
  patch 'articles/:id/dislike', to: 'articles#dislike', as: :dislike_article
  
  #get [URL QUE VAI SER], to: [NOME DO CONTROLLER#MÉTODO], as: [NOME QUE SERÁ REFERÊNCIA DA PÁGINA]
  
  #Rotas de SessionsControlles
  get 'users/crud', to: 'users#crud', as: :crud
    
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  
  delete 'logout', to: 'sessions#destroy', as: :logout
  
  #Rotas de UsersController
  get 'users', to: 'users#index', as: :users
  
  get 'users/new', to: 'users#new', as: :user_new
  post 'users/new', to: 'users#create'
  
  get 'users/:id', to: 'users#show', as: :user
  
  get 'users/edit/:id', to: 'users#edit', as: :user_edit
  patch 'users/edit/:id', to: 'users#update'
  
  delete 'users/destroy/:id', to: 'users#destroy', as: :user_destroy
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %>Sistema</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h3>Especialização de Back-end | IN Junior</h3>
      
      <section class="menu center">
        <%= link_to 'Usuários', users_path %>
        <%= link_to 'Novo Usuário', user_new_path %>
        <%= link_to 'Artigos', articles_path %>
        <%= link_to 'Comentários', comments_path %>
      </section>
      
      <% if logged_in? %>
        <p class="alert-login">Você está logado! <%= current_user.name %> <%=link_to "Logout", logout_path, method: :delete %></p>
      <% end %>
    </header>
    
    <%= yield %>
  </body>
</html>